# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c2727c7bde90ce9ec85130b1a7d74dad7023159443ba0136c32c41de42cda0b0dda8fc0a724708521c83709e1ad2c4971046ebd68e2cb3a7340c61ab94ac080

test:
  secret_key_base: e75b5280a917ac1625acb40a770677422c22c94844cdc431ab7c2adc646be3e0c3427e879b36cf11d07296f1a8b27f8b388c2aa4d10c68da104f909abc3d0861

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
